// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as AwsAmplify from "aws-amplify";
import * as AwsExportsJs from "../aws-exports.js";

var awsConfig = AwsExportsJs.default;

function configure(param) {
  AwsAmplify.default.configure(awsConfig);
  return /* () */0;
}

export {
  awsConfig ,
  configure ,
  
}
/* awsConfig Not a pure module */
