// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as AwsAmplify from "aws-amplify";

var logger = new AwsAmplify.Logger();

function info$1(param) {
  return info.onHubCapsule;
}

export {
  logger ,
  info$1 as info,
  
}
/* logger Not a pure module */
