// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as AwsAmplify from "aws-amplify";
import * as AwsExportsJs from "./aws-exports.js";

var awsConfig = AwsExportsJs.default;

function currentUserPoolUser(userPoolId) {
  return AwsAmplify.Auth.currentUserPoolUser(userPoolId).then((function (res) {
                return Promise.resolve(res);
              }));
}

function forgotPasswordSubmit(username, confirmationCode, password) {
  return AwsAmplify.Auth.forgotPasswordSubmit(username, confirmationCode, password).then((function (res) {
                return Promise.resolve(res);
              }));
}

function forgotPassword(username) {
  return AwsAmplify.Auth.forgotPassword(username).then((function (res) {
                return Promise.resolve(res);
              }));
}

function configure(param) {
  AwsAmplify.default.configure(awsConfig);
  return /* () */0;
}

function signOut(param) {
  AwsAmplify.Auth.configure();
  return /* () */0;
}

function signIn(username, password) {
  return AwsAmplify.Auth.signIn(username, password).then((function (res) {
                return Promise.resolve(res);
              }));
}

var currentAuthenticatedUser = AwsAmplify.Auth.currentAuthenticatedUser().then((function (res) {
        return Promise.resolve(res);
      }));

function confirmSignUp(username, confirmationCode) {
  return AwsAmplify.Auth.confirmSignUp(username, confirmationCode).then((function (res) {
                return Promise.resolve(res);
              }));
}

export {
  awsConfig ,
  currentUserPoolUser ,
  forgotPasswordSubmit ,
  forgotPassword ,
  configure ,
  signOut ,
  signIn ,
  currentAuthenticatedUser ,
  confirmSignUp ,
  
}
/* awsConfig Not a pure module */
