// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.bs.js";

Jest.test("addition", (function (param) {
        return Jest.Expect.toBe(7, Jest.Expect.expect(7));
      }));

export {
  
}
/*  Not a pure module */
