// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ecc2ac36-6020-4d08-b614-9cb15027fef7",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_qsBUOgK1h",
    "aws_user_pools_web_client_id": "6re1anr8srpkrj3867p1864g2n",
    "oauth": {}
};


export default awsmobile;
