// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Root from "./Root.bs.js";
import * as React from "react";
import * as Amplify from "./aws/Amplify.bs.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ServiceWorker from "./serviceWorker";
import * as IndexModuleCss from "./index.module.css";

var _css = IndexModuleCss;

function register_service_worker(prim) {
  ServiceWorker.register();
  return /* () */0;
}

function unregister_service_worker(prim) {
  ServiceWorker.unregister();
  return /* () */0;
}

Amplify.configure(/* () */0);

ReactDOMRe.renderToElementWithId(React.createElement(Root.make, { }), "root");

ServiceWorker.unregister();

export {
  _css ,
  register_service_worker ,
  unregister_service_worker ,
  
}
/* _css Not a pure module */
