// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as UserContext from "./auth/UserContext.bs.js";

function reducer(param, action) {
  if (action) {
    return /* record */[/* user : LoggedIn */[action[0]]];
  } else {
    return /* record */[/* user : Anonymous */0];
  }
}

function Root(Props) {
  var match = React.useReducer(reducer, /* record */[/* user : Anonymous */0]);
  return React.createElement(UserContext.Provider.make, UserContext.Provider.makeProps(/* tuple */[
                  match[0][/* user */0],
                  match[1]
                ], React.createElement(App.make, { }), /* () */0));
}

var make = Root;

export {
  reducer ,
  make ,
  
}
/* App Not a pure module */
