// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as React from "react";
import * as UserContext from "./auth/UserContext.bs.js";

function reducer(param, action) {
  if (action) {
    return {
            user: /* LoggedIn */{
              _0: action._0
            }
          };
  } else {
    return {
            user: /* Anonymous */0
          };
  }
}

function Root(Props) {
  var match = React.useReducer(reducer, {
        user: /* Anonymous */0
      });
  return React.createElement(UserContext.Provider.make, UserContext.Provider.makeProps([
                  match[0].user,
                  match[1]
                ], React.createElement(App.make, {}), undefined));
}

var make = Root;

export {
  reducer ,
  make ,
  
}
/* App Not a pure module */
